version: '3.9'
services:
  # Database service
  postgres:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # Backend service
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jinn-backend
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
